#include <stddef.h>

#include "command_internal.h"

static const command_entry command_table[] = {
    { "HELP", "Display command help", command_help },
    { "VERSION", "Display agent version", command_version },
    { "ROOT", "Display the project root", command_root },
    { "STATUS", "Display agent status", command_status },
    { "LIST", "List a directory: LIST [path]", command_list },
    { "TREE", "Display directory tree: TREE [path]", command_tree },
    { "READ", "Read lines: READ file [start [count]]", command_read },
    { "BUILD", "Build the current project", command_build },
    { "GITSTATUS", "Display Git status", command_gitstatus },
    { "GITDIFF", "Display uncommitted source changes", command_gitdiff },
    { "EDIT", "Edit a file: EDIT file", command_edit },
    { "CHAT", "Continue an OpenAI conversation: CHAT prompt", command_chat },
    { "CHAT/RESET", "Reset the OpenAI conversation", command_chat_reset },
    { "REVIEW", "Review source with OpenAI: REVIEW file", command_review },
    { "AGENT", "Run read-only AI agent: AGENT goal", command_agent },
    { "AGENT/WRITE",
      "Run guarded write agent: AGENT/WRITE goal",
      command_agent_write },
    { "AGENT/BUILD",
      "Run controlled project build analysis: AGENT/BUILD goal",
      command_agent_build },
    { "AGENT/FIX",
      "Apply one confirmed fix and build: AGENT/FIX goal",
      command_agent_fix },
    { "AGENT/RETRY",
      "Retry one supervised fix using prior build diagnostics: "
      "AGENT/RETRY goal",
      command_agent_retry },
    { "AGENT/SELFTEST",
      "Run non-destructive agent checks",
      command_agent_selftest },
    { "AGENT/STATUS",
      "Show agent capabilities and recent workflow state",
      command_agent_status },
    { "AGENT/VERIFY",
      "Run safety checks and a controlled build",
      command_agent_verify },
    { "AGENT/LOG",
      "Display the structured local activity log",
      command_agent_log },
    { "AGENT/LOG/OLD",
      "Display the rotated activity log",
      command_agent_log_old },
    { "AGENT/LOG/CLEAR",
      "Clear the active activity log with confirmation",
      command_agent_log_clear },
    { "AGENT/METRICS",
      "Summarize structured activity metrics",
      command_agent_metrics },
    { "AGENT/STATE",
      "Display validated persistent workflow state",
      command_agent_state },
    { "AGENT/STATE/CLEAR",
      "Clear persisted workflow state with confirmation",
      command_agent_state_clear },
    { "AGENT/CREATE",
      "Create one new confirmed project file: AGENT/CREATE goal",
      command_agent_create },
    { "AGENT/PLAN",
      "Create a read-only implementation plan: AGENT/PLAN goal",
      command_agent_plan },
    { "AGENT/PLAN/SHOW",
      "Display the saved implementation plan",
      command_agent_plan_show },
    { "AGENT/PLAN/CLEAR",
      "Clear the saved implementation plan with confirmation",
      command_agent_plan_clear },
    { "AGENT/PLAN/VALIDATE",
      "Validate saved-plan file fingerprints",
      command_agent_plan_validate },
    { "AGENT/EXECUTE",
      "Execute one validated saved-plan operation",
      command_agent_execute },
    { "ASK", "Send a prompt to OpenAI: ASK prompt", command_ask },
    { "SEARCH", "Search a file: SEARCH file \"text\"", command_search },
    { "PATCH",
      "Replace exact text: PATCH file \"old\" \"new\"",
      command_patch },
    { "QUIT", "Exit OVMS Agent", command_quit },
    { "EXIT", "Exit OVMS Agent", command_quit },
    { NULL, NULL, NULL }
};

const command_entry *command_table_get(void)
{
    return command_table;
}
