$ CC/STANDARD=ANSI89 MAIN.C
$ IF $SEVERITY .GE. 2 THEN EXIT $STATUS
$ CC/STANDARD=ANSI89 STORAGE.C
$ IF $SEVERITY .GE. 2 THEN EXIT $STATUS
$ LINK MAIN.OBJ,STORAGE.OBJ
$ IF $SEVERITY .GE. 2 THEN EXIT $STATUS
$ EXIT 1
